# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@score_baselibs//:bazel/unit_tests.bzl", "cc_gtest_unit_test", "cc_unit_test_suites_for_host_and_qnx")
load("//score/mw:common_features.bzl", "COMPILER_WARNING_FEATURES")

cc_library(
    name = "plumbing",
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com:__subpackages__",
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":binding_runtime_factory",
        ":proxy_binding_factory",
        ":sample_allocatee_ptr",
        ":sample_ptr",
        ":skeleton_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_method_binding_factory",
    srcs = ["skeleton_method_binding_factory.cpp"],
    hdrs = ["skeleton_method_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        "skeleton_method_binding_factory_impl",
        ":i_skeleton_method_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_skeleton_method_binding_factory",
    srcs = ["i_skeleton_method_binding_factory.cpp"],
    hdrs = ["i_skeleton_method_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:skeleton_base",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_method_binding_factory_impl",
    srcs = ["skeleton_method_binding_factory_impl.cpp"],
    hdrs = ["skeleton_method_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],
    deps = [
        ":i_skeleton_method_binding_factory",
        ":skeleton_service_element_binding_factory_impl",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_method_binding_factory_mock",
    testonly = True,
    srcs = ["skeleton_method_binding_factory_mock.cpp"],
    hdrs = ["skeleton_method_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":i_skeleton_method_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_gtest_unit_test(
    name = "skeleton_method_binding_factory_test",
    srcs = [
        "skeleton_method_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        ":skeleton_method_binding_factory",
        "//score/mw/com/impl/bindings/lola/test:skeleton_test_resources",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "//score/mw/com/impl/test:dummy_instance_identifier_builder",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
    ],
)

cc_library(
    name = "binding_runtime_factory",
    srcs = ["binding_runtime_factory.cpp"],
    hdrs = ["binding_runtime_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl/bindings/lola",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/concurrency:executor",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_proxy_binding_factory",
    srcs = ["i_proxy_binding_factory.cpp"],
    hdrs = ["i_proxy_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:handle_type",
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:proxy_binding",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_proxy_event_binding_factory",
    srcs = ["i_proxy_event_binding_factory.cpp"],
    hdrs = ["i_proxy_event_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:proxy_base",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_proxy_field_binding_factory",
    srcs = ["i_proxy_field_binding_factory.cpp"],
    hdrs = ["i_proxy_field_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:proxy_base",
        "//score/mw/com/impl/methods:proxy_method_binding",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_proxy_method_binding_factory",
    srcs = ["i_proxy_method_binding_factory.cpp"],
    hdrs = ["i_proxy_method_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:proxy_base",
        "//score/mw/com/impl/methods:proxy_method_binding",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_skeleton_binding_factory",
    srcs = ["i_skeleton_binding_factory.cpp"],
    hdrs = ["i_skeleton_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:skeleton_binding",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_skeleton_event_binding_factory",
    srcs = ["i_skeleton_event_binding_factory.cpp"],
    hdrs = ["i_skeleton_event_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:skeleton_base",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "i_skeleton_field_binding_factory",
    srcs = ["i_skeleton_field_binding_factory.cpp"],
    hdrs = ["i_skeleton_field_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:skeleton_base",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_binding_factory_impl",
    srcs = ["proxy_binding_factory_impl.cpp"],
    hdrs = ["proxy_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        ":i_proxy_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "lola_proxy_element_building_blocks",
    srcs = ["lola_proxy_element_building_blocks.cpp"],
    hdrs = ["lola_proxy_element_building_blocks.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:proxy_base",
        "//score/mw/com/impl/bindings/lola",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_event_binding_factory_impl",
    srcs = ["proxy_event_binding_factory_impl.cpp"],
    hdrs = ["proxy_event_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        ":i_proxy_event_binding_factory",
        ":lola_proxy_element_building_blocks",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_field_binding_factory_impl",
    srcs = ["proxy_field_binding_factory_impl.cpp"],
    hdrs = ["proxy_field_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],
    deps = [
        ":i_proxy_field_binding_factory",
        ":lola_proxy_element_building_blocks",
        ":proxy_method_binding_factory",
        "//score/mw/com/impl:method_type",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_method_binding_factory_impl",
    srcs = ["proxy_method_binding_factory_impl.cpp"],
    hdrs = ["proxy_method_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl/plumbing:__subpackages__",
    ],
    deps = [
        ":i_proxy_method_binding_factory",
        ":lola_proxy_element_building_blocks",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_binding_factory_impl",
    srcs = ["skeleton_binding_factory_impl.cpp"],
    hdrs = ["skeleton_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "//score/mw/com/impl/bindings/lola",
        "//score/mw/com/impl/bindings/lola:partial_restart_path_builder",
        "//score/mw/com/impl/bindings/lola:shm_path_builder",
        "@score_baselibs//score/mw/log",
    ],
    tags = ["FFI"],
    deps = [
        ":i_skeleton_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_service_element_binding_factory_impl",
    srcs = ["skeleton_service_element_binding_factory_impl.cpp"],
    hdrs = ["skeleton_service_element_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    deps = [
        "//score/mw/com/impl:skeleton_base",
        "//score/mw/com/impl/bindings/lola",
        "//score/mw/com/impl/configuration",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_event_binding_factory_impl",
    srcs = ["skeleton_event_binding_factory_impl.cpp"],
    hdrs = ["skeleton_event_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],
    deps = [
        ":i_skeleton_event_binding_factory",
        ":skeleton_service_element_binding_factory_impl",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_field_binding_factory_impl",
    srcs = ["skeleton_field_binding_factory_impl.cpp"],
    hdrs = ["skeleton_field_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],
    deps = [
        ":i_skeleton_field_binding_factory",
        ":skeleton_service_element_binding_factory_impl",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_binding_factory",
    srcs = ["proxy_binding_factory.cpp"],
    hdrs = ["proxy_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "proxy_binding_factory_impl",
    ],
    tags = ["FFI"],
    deps = [
        ":i_proxy_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_event_binding_factory",
    srcs = ["proxy_event_binding_factory.cpp"],
    hdrs = ["proxy_event_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    deps = [
        "proxy_event_binding_factory_impl",
        ":i_proxy_event_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_field_binding_factory",
    srcs = ["proxy_field_binding_factory.cpp"],
    hdrs = ["proxy_field_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    deps = [
        "proxy_field_binding_factory_impl",
        ":i_proxy_field_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_method_binding_factory",
    srcs = ["proxy_method_binding_factory.cpp"],
    hdrs = ["proxy_method_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":i_proxy_method_binding_factory",
        ":proxy_method_binding_factory_impl",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_binding_factory",
    srcs = ["skeleton_binding_factory.cpp"],
    hdrs = ["skeleton_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "skeleton_binding_factory_impl",
    ],
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":i_skeleton_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_event_binding_factory",
    srcs = ["skeleton_event_binding_factory.cpp"],
    hdrs = ["skeleton_event_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    deps = [
        "skeleton_event_binding_factory_impl",
        ":i_skeleton_event_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "skeleton_field_binding_factory",
    srcs = ["skeleton_field_binding_factory.cpp"],
    hdrs = ["skeleton_field_binding_factory.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    deps = [
        "skeleton_field_binding_factory_impl",
        ":i_skeleton_field_binding_factory",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "proxy_binding_factory_mock",
    testonly = True,
    srcs = ["proxy_binding_factory_mock.cpp"],
    hdrs = ["proxy_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//visibility:public",  # platform_only
    ],
    deps = [
        ":i_proxy_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "proxy_event_binding_factory_mock",
    testonly = True,
    srcs = ["proxy_event_binding_factory_mock.cpp"],
    hdrs = ["proxy_event_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//visibility:public",  # platform_only
    ],
    deps = [
        ":i_proxy_event_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "proxy_field_binding_factory_mock",
    testonly = True,
    srcs = ["proxy_field_binding_factory_mock.cpp"],
    hdrs = ["proxy_field_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//visibility:public",  # platform_only
    ],
    deps = [
        ":i_proxy_field_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "proxy_method_binding_factory_mock",
    testonly = True,
    srcs = ["proxy_method_binding_factory_mock.cpp"],
    hdrs = ["proxy_method_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":i_proxy_method_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "skeleton_binding_factory_mock",
    testonly = True,
    srcs = ["skeleton_binding_factory_mock.cpp"],
    hdrs = ["skeleton_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//visibility:public",  # platform_only
    ],
    deps = [
        ":i_skeleton_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "skeleton_event_binding_factory_mock",
    testonly = True,
    srcs = ["skeleton_event_binding_factory_mock.cpp"],
    hdrs = ["skeleton_event_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//visibility:public",  # platform_only
    ],
    deps = [
        ":i_skeleton_event_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "skeleton_field_binding_factory_mock",
    testonly = True,
    srcs = ["skeleton_field_binding_factory_mock.cpp"],
    hdrs = ["skeleton_field_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//visibility:public",  # platform_only
    ],
    deps = [
        ":i_skeleton_field_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "generic_skeleton_event_binding_factory_impl",
    srcs = ["generic_skeleton_event_binding_factory_impl.cpp"],
    hdrs = ["generic_skeleton_event_binding_factory_impl.h"],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = ["//score/mw/com/impl/bindings/lola"],
    tags = ["FFI"],  # Increased visibility as it's now in score::mw::com::impl namespace
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":skeleton_service_element_binding_factory_impl",
        "//score/mw/com/impl:i_generic_skeleton_event_binding_factory",
        "//score/mw/com/impl/bindings/lola:generic_skeleton_event",
    ],
)

cc_library(
    name = "generic_skeleton_event_binding_factory",
    srcs = ["generic_skeleton_event_binding_factory.cpp"],
    hdrs = [
        "generic_skeleton_event_binding_factory.h",
        "skeleton_service_element_binding_factory_impl.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        ":generic_skeleton_event_binding_factory_impl",
    ],
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        # Removed unnecessary dependency
        "//score/mw/com/impl:i_generic_skeleton_event_binding_factory",
    ],
)

cc_library(
    name = "generic_skeleton_event_binding_factory_mock",
    testonly = True,
    srcs = ["generic_skeleton_event_binding_factory_mock.cpp"],
    hdrs = ["generic_skeleton_event_binding_factory_mock.h"],
    features = COMPILER_WARNING_FEATURES,
    visibility = [
        "//visibility:public",  # platform_only
    ],
    deps = [
        "//score/mw/com/impl:i_generic_skeleton_event_binding_factory",
        "@googletest//:gtest",
    ],
)

cc_library(
    name = "runtime",
    srcs = [
        "binding_runtime_factory.cpp",
    ],
    hdrs = [
        "binding_runtime_factory.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    implementation_deps = [
        "//score/mw/com/impl/bindings/lola/tracing:tracing_runtime",
    ],
    tags = ["FFI"],
    visibility = [
        "//score/mw/com:__subpackages__",
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        "//score/mw/com/impl:runtime_interfaces",
        "//score/mw/com/impl/bindings/lola:runtime",
        "//score/mw/com/impl/configuration",
        "//score/mw/com/impl/tracing/configuration:tracing_filter_config",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "event",
    srcs = [
    ],
    hdrs = [
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":proxy_event_binding_factory",
        ":sample_allocatee_ptr",
        ":skeleton_event_binding_factory",
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:proxy_base",
        "//score/mw/com/impl:skeleton_base",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "field",
    srcs = [
    ],
    hdrs = [
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":proxy_field_binding_factory",
        ":sample_allocatee_ptr",
        ":skeleton_field_binding_factory",
        "//score/mw/com/impl:instance_identifier",
        "//score/mw/com/impl:proxy_base",
        "//score/mw/com/impl:skeleton_base",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_library(
    name = "sample_allocatee_ptr",
    srcs = [
        "sample_allocatee_ptr.cpp",
    ],
    hdrs = [
        "sample_allocatee_ptr.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl:__subpackages__"],
    deps = [
        "//score/mw/com/impl/bindings/lola:event",
        "//score/mw/com/impl/bindings/mock_binding:sample_allocatee_ptr",
    ],
)

cc_library(
    name = "sample_ptr",
    srcs = [
        "sample_ptr.cpp",
    ],
    hdrs = [
        "sample_ptr.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//score/mw/com/impl:__subpackages__"],
    deps = [
        "//score/mw/com/impl:sample_reference_tracker",
        "//score/mw/com/impl/bindings/lola:event",
        "//score/mw/com/impl/bindings/mock_binding:sample_ptr",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_gtest_unit_test(
    name = "proxy_method_binding_factory_test",
    srcs = [
        "proxy_method_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        # These tests catch exceptions instead of using gtest EXPECT_DEATH so we disable aborts_upon_exception.
        "-aborts_upon_exception",
    ],
    deps = [
        ":proxy_method_binding_factory",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "//score/mw/com/impl/test:dummy_instance_identifier_builder",
        "@score_baselibs//score/language/futurecpp:futurecpp_test_support",
    ],
)

cc_gtest_unit_test(
    name = "proxy_event_field_binding_factory_test",
    srcs = [
        "proxy_event_field_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "//score/mw/com/impl/test:dummy_instance_identifier_builder",
    ],
)

cc_gtest_unit_test(
    name = "proxy_event_binding_factory_test",
    srcs = [
        "proxy_event_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":proxy_event_binding_factory",
    ],
)

cc_gtest_unit_test(
    name = "proxy_field_binding_factory_test",
    srcs = [
        "proxy_field_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":proxy_field_binding_factory",
    ],
)

cc_gtest_unit_test(
    name = "skeleton_service_element_binding_factory_test",
    srcs = [
        "skeleton_service_element_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":skeleton_event_binding_factory",
        ":skeleton_field_binding_factory",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "//score/mw/com/impl/test:dummy_instance_identifier_builder",
    ],
)

cc_gtest_unit_test(
    name = "skeleton_event_binding_factory_test",
    srcs = [
        "skeleton_event_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":skeleton_event_binding_factory",
    ],
)

cc_gtest_unit_test(
    name = "skeleton_field_binding_factory_test",
    srcs = [
        "skeleton_field_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":skeleton_field_binding_factory",
    ],
)

cc_gtest_unit_test(
    name = "binding_runtime_factory_test",
    srcs = [
        "binding_runtime_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        ":binding_runtime_factory",
        "//score/mw/com/impl/configuration/test:configuration_store",
        "//score/mw/com/impl/test:dummy_instance_identifier_builder",
    ],
)

cc_test(
    name = "unit_test",
    size = "medium",
    srcs = [
        "proxy_binding_factory_test.cpp",
        "sample_allocatee_ptr_test.cpp",
        "sample_ptr_test.cpp",
        "skeleton_binding_factory_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    tags = ["unit"],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
    deps = [
        ":event",
        ":plumbing",
        ":proxy_binding_factory_mock",
        "//score/mw/com/impl:runtime_mock",
        "//score/mw/com/impl/bindings/lola:runtime_mock",
        "//score/mw/com/impl/bindings/lola/test:proxy_event_test_resources",
        "//score/mw/com/impl/bindings/lola/test_doubles",
        "//score/mw/com/impl/bindings/mock_binding",
        "//score/mw/com/impl/test:dummy_instance_identifier_builder",
        "//score/mw/com/impl/test:runtime_mock_guard",
        "@googletest//:gtest_main",
        "@score_baselibs//score/language/safecpp/coverage_termination_handler",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/os/mocklib:fcntl_mock",
    ],
)

cc_unit_test_suites_for_host_and_qnx(
    name = "unit_test_suite",
    cc_unit_tests = [
        ":proxy_event_binding_factory_test",
        ":proxy_method_binding_factory_test",
        ":proxy_field_binding_factory_test",
        ":proxy_event_field_binding_factory_test",
        ":skeleton_method_binding_factory_test",
        ":binding_runtime_factory_test",
        ":skeleton_event_binding_factory_test",
        ":skeleton_field_binding_factory_test",
        ":skeleton_service_element_binding_factory_test",
        ":unit_test",
    ],
    visibility = [
        "//score/mw/com/impl:__subpackages__",
    ],
)
